const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function art(){const rectangles=[],people=[],ctx={fillRect(...a){assert.ok(a.every(Number.isFinite));rectangles.push([this.fillStyle,...a]);},fillText(){},save(){},restore(){},translate(x,y){people.push([x,y]);},scale(){}};const c={window:null};c.window=c;vm.createContext(c);for(const file of ['i18n','campus','festival','art'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/'+file+'.js'),'utf8'),c);return {c,ctx,rectangles,people};}
test('room patterns are stable within a night, irregular and different next night',()=>{const {c,ctx}=art(),campus=c.createCampusArt(ctx);const pattern=s=>Array.from({length:252},(_,i)=>campus.roomLit(i,s));const a=pattern(123),b=pattern(123+0x9e3779b9);assert.deepEqual(a,pattern(123));assert.notDeepEqual(a,b);assert.ok(a.filter(Boolean).length>35&&a.filter(Boolean).length<95);assert.ok(a.some((v,i)=>i&&v&&a[i-1]));assert.ok(a.some((v,i)=>i>4&&!v&&!a[i-1]&&!a[i-2]&&!a[i-3]));});
test('festival queue has no teleports at old reset and route boundaries',()=>{const {c,ctx,people}=art(),f=c.createFestivalArt(ctx);for(const t of [3,4,12,24,28]){people.length=0;f.draw(0,t-.001,0,c.I18N.tr);const before=people.slice();people.length=0;f.draw(0,t+.001,0,c.I18N.tr);assert.equal(people.length,before.length);for(const [x,y] of before)assert.ok(people.some(([a,b])=>Math.hypot(a-x,b-y)<3));}});
test('all campus scenes render in both phases with finite geometry',()=>{const {c,ctx}=art(),a=c.createArt(ctx);for(const n of [0,.5,1])for(let world=0;world<39000;world+=900)a.scene(world,1200,c.I18N.tr,n,28,987);});
test('festival appearance survives sunrise and sunset, resets on exit or restart',()=>{for(const initial of [0,1]){const {c,ctx}=art(),calls=[];vm.runInContext('Math.random=()=>.999',c);c.createFestivalArt=()=>({draw(x,t,n){calls.push(n);},lights(){},campusLife(){}});const a=c.createArt(ctx);a.scene(3300,1200,c.I18N.tr,initial,1);calls.length=0;for(const n of [.49,.51,1-initial])a.scene(3301,1200,c.I18N.tr,n,2);assert.ok(calls.length);assert.ok(calls.every(n=>n===initial));a.scene(8000,1200,c.I18N.tr,1-initial,3);calls.length=0;a.scene(3300,1200,c.I18N.tr,1-initial,4);assert.ok(calls.every(n=>n===1-initial));a.resetScene();calls.length=0;a.scene(3300,1200,c.I18N.tr,initial,0);assert.ok(calls.every(n=>n===initial));}});

test('venues leave gaps and cannot repeat within the previous five stops',()=>{const {c,ctx}=art(),a=c.createArt(ctx);let all=[];for(let offset=0;offset<80000;offset+=500){for(const l of a.routeFor(offset,1200))if(!all.some(v=>v.x===l.x))all.push({x:l.x,type:l.type});}for(let i=1;i<all.length;i++){assert.ok(!all.slice(Math.max(0,i-5),i).some(l=>l.type===all[i].type));const w=all[i-1].type===11?980:all[i-1].type===0?540:500;assert.ok(all[i].x-all[i-1].x-w>=380);}assert.ok(all.length>50);});
test('NPC groups cover every gender ordering for two, three and four students',()=>{const {c,ctx}=art(),f=c.createFestivalArt(ctx),seen={2:new Set(),3:new Set(),4:new Set()};for(let i=0;i<64;i++){const g=f.groupComposition(i);seen[g.count]?.add(g.mask);}for(const n of [2,3,4])assert.equal(seen[n].size,2**n);});
