const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');

function game(){
  const elements=new Map(),events={},saved=new Map();
  function element(id){if(!elements.has(id))elements.set(id,{textContent:'',dataset:{},classList:{toggle(){}},setAttribute(k,v){this[k]=v;},listeners:{},addEventListener(k,v){this.listeners[k]=v;},setPointerCapture(){},focus(){},showModal(){this.open=true;},close(){this.open=false;},getContext:()=>({clearRect(){}}),getBoundingClientRect:()=>({width:1200,height:450})});return elements.get(id);}
  const window={dispatchEvent(){}};
  const context={window,document:{querySelector:element,querySelectorAll:()=>[],documentElement:{setAttribute(){}},addEventListener(){},modelContext:{registerTool(tool){context.tool=tool;}}},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},addEventListener:(k,v)=>events[k]=v,requestAnimationFrame(){},CustomEvent:class{constructor(type,data){this.type=type;this.detail=data.detail;}},console};
  vm.createContext(context);
  vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/i18n.js'),'utf8'),context);context.I18N=window.I18N;
  context.createArt=()=>({scene:()=>0,student(){},coffee(){},powerbank(){},obstacle(){},r(){},txt(){}});
  const source=fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8');
  // Test-only access to closure state; no debug controls are shipped to the browser.
  const hook=`window.test={start,pause,jump,fire,update,setLanguage,setCharacter,spawnItem,playerBox,hit,collect,collectPowerbank,syncPhase,
    set(s){if('distance' in s)distance=s.distance;if('charge' in s)charge=s.charge;if('hp' in s)hp=s.hp;if('duck' in s)duck=s.duck;if(s.player)Object.assign(player,s.player);if(s.obstacles)obstacles=s.obstacles;if(s.coffees)coffees=s.coffees;if(s.powerbanks)powerbanks=s.powerbanks;},
    state(){return {speed,lightSeed,night,nightBlend,hp,mode,kills,collected,lang,charge,character,score:score(),player,obstacles,coffees,powerbanks,bullets,invincible};}};`;
  vm.runInContext(source.replace(/\}\)\(\);\s*$/,hook+'})();'),context);
  return {api:window.test,elements,context,events};
}
test('ground coffee heals once, caps at three and disappears',()=>{const {api}=game();api.start();api.set({hp:1,coffees:[{x:120,y:309,w:32,h:31}]});api.update(1/120);assert.equal(api.state().hp,2);assert.equal(api.state().collected,1);assert.equal(api.state().coffees.length,0);api.update(1/120);assert.equal(api.state().hp,2);api.collect({});api.collect({});assert.equal(api.state().hp,3);});
test('jumping over coffee does not collect it',()=>{const {api}=game();api.start();api.set({player:{y:220},coffees:[{x:120,y:309,w:32,h:31}]});api.update(1/120);assert.equal(api.state().collected,0);});
test('powerbank and coffee occupy separate safe slots',()=>{const {api}=game();api.start();for(let i=0;i<6;i++)api.spawnItem();assert.equal(api.state().obstacles.length,4);assert.equal(api.state().coffees.length,1);assert.equal(api.state().powerbanks.length,1);assert.equal(api.state().obstacles[2].type,'block');});
test('standing hits overhead 404; ducking passes below',()=>{for(const duck of [false,true]){const {api}=game();api.start();api.set({duck,obstacles:[{type:'fly',x:120,y:239,w:72,h:27}]});api.update(1/120);assert.equal(api.state().hp,duck?3:2);}});
test('boar collision costs a heart; invulnerability prevents duplicate damage',()=>{const {api}=game();api.start();api.set({obstacles:[{type:'boar',x:120,y:302,w:63,h:38},{type:'block',x:125,y:278,w:91,h:62}]});api.update(1/120);assert.equal(api.state().hp,2);api.update(1/120);assert.equal(api.state().hp,2);});
test('bullets remove bugs but do not kill boars',()=>{for(const type of ['bug','boar']){const {api}=game();api.start();api.fire();api.set({obstacles:[{type,x:195,y:290,w:50,h:40}]});api.update(1/120);assert.equal(api.state().kills,type==='bug'?1:0);}});
test('language switch preserves run and translates paused overlay',()=>{const {api,elements}=game();api.start();api.set({hp:2});api.update(.1);const before=api.state().score;api.setLanguage('en');assert.equal(api.state().hp,2);assert.equal(api.state().score,before);assert.equal(api.state().mode,'running');api.pause();assert.equal(elements.get('#overlayTitle').textContent,'Coffee break.');api.setLanguage('tr');assert.equal(elements.get('#overlayTitle').textContent,'Kahve molası.');assert.equal(api.state().mode,'paused');});
test('game-over and restart restore all run state',()=>{const {api}=game();api.start();api.set({hp:1,obstacles:[{type:'block',x:120,y:278,w:91,h:62}]});api.update(1/120);assert.equal(api.state().mode,'over');api.start();assert.equal(api.state().hp,3);assert.equal(api.state().score,0);assert.equal(api.state().collected,0);assert.equal(api.state().obstacles.length,0);});
test('read-only WebMCP returns run state and rejects malformed input',()=>{const {api,context}=game();api.start();assert.equal(context.tool.execute({}).health,3);assert.throws(()=>context.tool.execute({health:99}));assert.throws(()=>context.tool.execute([]));assert.equal(api.state().hp,3);});
test('all translated keys match and sound API is absent',()=>{const {context}=game();assert.deepEqual(Object.keys(context.I18N.tr).sort(),Object.keys(context.I18N.en).sort());const src=fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8');assert.doesNotMatch(src,/AudioContext|Oscillator|new Audio\(/);});
test('ten shots drain battery; cooldown and empty shots consume no extra charge',()=>{const {api}=game();api.start();for(let i=0;i<10;i++){api.fire();const n=api.state().charge;api.fire();assert.equal(api.state().charge,n);api.update(.3);}assert.equal(api.state().charge,0);const count=api.state().bullets.length;api.fire();assert.equal(api.state().bullets.length,count);assert.equal(api.state().charge,0);});
test('powerbank restores two once, caps at ten, and enables firing again',()=>{const {api}=game();api.start();api.set({charge:0,powerbanks:[{x:120,y:309,w:30,h:31}]});api.update(1/120);assert.equal(api.state().charge,2);assert.equal(api.state().powerbanks.length,0);api.fire();assert.equal(api.state().charge,1);api.set({charge:9});api.collectPowerbank({});assert.equal(api.state().charge,10);api.start();assert.equal(api.state().charge,10);});
test('both characters can be selected before a run, never during one',()=>{const {api,context}=game();api.setCharacter('female');assert.equal(api.state().character,'female');api.start();api.setCharacter('male');assert.equal(api.state().character,'female');api.pause();api.setCharacter('male');assert.equal(api.state().character,'female');assert.equal(context.tool.execute({}).character,'female');});
test('day/night flips at 1200, 2400 and 3600 and restart begins at day',()=>{const {api}=game();api.start();for(const [score,expected] of [[1199,false],[1200,true],[2399,true],[2400,false],[3600,true]]){api.set({distance:score*12});api.syncPhase(0);assert.equal(api.state().night,expected);}api.start();assert.equal(api.state().night,false);assert.equal(api.state().nightBlend,0);});
test('phase changes preserve existing hazards and their reveal state',()=>{const {api}=game();api.start();for(const distance of [14400,28800]){const obstacles=[{type:'quiz',x:500,reveal:.7},{type:'boar',x:650},{type:'fly',x:800},{type:'block',x:900},{type:'bug',x:1000}];api.set({distance,obstacles});api.syncPhase(.1);assert.equal(api.state().obstacles,obstacles);assert.equal(api.state().obstacles[0].reveal,.7);}});
test('day spawns only exams and bugs; night spawns only boars, flies and bugs',()=>{for(const night of [false,true]){const {api}=game();api.start();if(night){api.set({distance:14400});api.syncPhase(0);}for(let i=0;i<60;i++)api.spawnItem();const types=new Set(Array.from(api.state().obstacles,o=>o.type));assert.ok(types.has('bug'));assert.ok(!types.has(night?'block':'fly'));assert.ok(!types.has(night?'block':'boar'));if(!night)assert.ok(types.has('block'));}});
test('flies and exams cannot be destroyed by bullets',()=>{for(const type of ['fly','block']){const {api}=game();api.start();api.fire();api.set({obstacles:[{type,x:195,y:290,w:50,h:40}]});api.update(1/120);assert.equal(api.state().kills,0);assert.equal(api.state().obstacles.length,1);}});
test('quiz reveals with reaction time, is duckable and survives nightfall',()=>{for(const duck of [false,true]){const {api}=game();api.start();api.set({duck,obstacles:[{type:'quiz',x:610,y:239,w:112,h:27,reveal:0}]});api.update(.01);assert.ok(api.state().obstacles[0].reveal>0);assert.ok(api.state().obstacles[0].x-api.state().player.x>450);api.set({obstacles:[{type:'quiz',x:120,y:239,w:112,h:27,reveal:1}]});api.update(.01);assert.equal(api.state().hp,duck?3:2);api.set({distance:14400,obstacles:[{type:'quiz',x:500}]});api.syncPhase(0);assert.equal(api.state().obstacles.length,1);}});

test('night seed changes only on entering a new night',()=>{const {api}=game();api.start();let seed=api.state().lightSeed;api.update(.1);assert.equal(api.state().lightSeed,seed);api.set({distance:14400});api.syncPhase(0);assert.notEqual(api.state().lightSeed,seed);seed=api.state().lightSeed;api.syncPhase(.1);assert.equal(api.state().lightSeed,seed);api.set({distance:28800});api.syncPhase(0);assert.equal(api.state().lightSeed,seed);api.set({distance:43200});api.syncPhase(0);assert.notEqual(api.state().lightSeed,seed);});
test('sunrise and sunset take ten seconds with no instantaneous jump',()=>{const {api}=game();api.start();api.set({distance:14400});api.syncPhase(0);assert.equal(api.state().nightBlend,0);for(let i=0;i<50;i++)api.syncPhase(.1);assert.ok(Math.abs(api.state().nightBlend-.5)<.001);for(let i=0;i<51;i++)api.syncPhase(.1);assert.equal(api.state().nightBlend,1);api.set({distance:28800});api.syncPhase(0);assert.equal(api.state().nightBlend,1);for(let i=0;i<50;i++)api.syncPhase(.1);assert.ok(Math.abs(api.state().nightBlend-.5)<.001);});

test('each complete 2400-score cycle increases the target speed',()=>{const {api}=game();api.start();api.set({distance:28800});for(let i=0;i<120;i++)api.update(1/120);const one=api.state().speed;api.start();for(let i=0;i<120;i++)api.update(1/120);assert.ok(one>api.state().speed+20);api.set({distance:57600});for(let i=0;i<120;i++)api.update(1/120);assert.ok(api.state().speed>one);});

test('touch controls suppress callouts and cancel a held duck safely',()=>{const {api,elements}=game();api.start();let prevented=0;const e={pointerId:1,preventDefault(){prevented++;}};for(const id of ['#jumpTouch','#duckTouch','#fireTouch'])for(const event of ['contextmenu','selectstart','dragstart'])elements.get(id).listeners[event](e);assert.equal(prevented,9);const duck=elements.get('#duckTouch');duck.listeners.pointerdown(e);assert.equal(api.playerBox().h,69);duck.listeners.pointercancel(e);assert.equal(api.playerBox().h,77);});

test('theme switching preserves the run and updates accessible label',()=>{const {api,elements}=game();api.start();api.set({hp:2,charge:6});elements.get('#themeToggle').onclick();assert.equal(elements.get('#themeToggle')['aria-pressed'],'true');assert.equal(api.state().hp,2);assert.equal(api.state().charge,6);api.setLanguage('en');assert.equal(elements.get('#themeToggle')['aria-label'],'Dark theme');});
test('results show final score and allow returning to character selection',()=>{const {api,elements}=game();api.start();api.set({hp:1,distance:1200,obstacles:[{type:'block',x:120,y:278,w:91,h:62}]});api.update(.01);assert.equal(api.state().mode,'over');assert.equal(elements.get('#runResults').hidden,false);assert.equal(elements.get('#resultScore').textContent,'00100');elements.get('#chooseAgain').onclick();assert.equal(api.state().mode,'ready');assert.equal(elements.get('#characterPicker').hidden,false);});
test('quizzes block every jump height but leave a crouching gap',()=>{for(const night of [false]){const {api}=game();api.start();for(let i=0;i<120;i++)api.spawnItem();const hazards=api.state().obstacles.filter(o=>o.type==='quiz');assert.ok(hazards.length);for(const o of hazards){o.x=115;for(let y=215;y<=340;y+=5){api.set({player:{y},duck:false});assert.ok(api.hit(api.playerBox(),o),`${o.type} jump y=${y}`);}api.set({player:{y:340},duck:true});assert.equal(api.hit(api.playerBox(),o),false);}}});

test('flies retain original low flight geometry',()=>{const {api}=game();api.start();api.set({distance:14400});api.syncPhase(0);for(let i=0;i<120;i++)api.spawnItem();const flies=api.state().obstacles.filter(o=>o.type==='fly');assert.ok(flies.length);for(const f of flies){assert.equal(f.y,239);assert.equal(f.h,27);}});
